<?php

namespace App\Controller;

use App\Form\EditProfilType;
use App\Form\ItemType;
use App\Entity\User ;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProfilController extends AbstractController
{
    /**
     * @Route("/profil", name="app_profil")
     */
    public function index(): Response
    {
        return $this->render('profil/index.html.twig', [
            'controller_name' => 'ProfilController',
        ]);
    }
    /**
     * @Route ("/profil/show", name="show")
     */
    public function show()
    {

        return $this->render('profil/index.html.twig');
    }

    /**
     * @Route ("/profil/edit",name="ProfilEdit")
     */
    public function editProfile(Request $request){
        //$user= new User();
        $user=$this->getUser();
        $form=$this->createForm(EditProfilType::class , $user);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
            $this->addFlash('message','Profil mis a jour');
            return $this->redirectToRoute('show');
        }
        return $this->render('profil/edit.html.twig',[
            'form'=>$form->createView()
        ]);
    }
    /**
     * @Route("/new", name="photo", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        //$user = new User();
        $user=$this->getUser();
        $form = $this->createForm(ItemType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //$file = $user->getImage();
            $file=$form->get('image')->getData();
            $fileName =md5(uniqid()).'.'.$file->guessExtension();

            // moves the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('upload_directory'),
                $fileName
            );

            $user->setImage($fileName);
            $em=$this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();


            return $this->redirectToRoute('show');
        }

        return $this->render('profil/editPhoto.html.twig', [
            
            'form' => $form->createView(),
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

}
